name:                confie
version:             0.1.0.0
license:             BSD3
author:              "Dimitis Spythouris"
copyright:           "2020 Dimitris Spythouris"
description:         Please see the README on GitLab

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.3.1
- conf >= 0.1.1.0

executables:
  confie:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -static
    - -with-rtsopts=-N
    
