[pacman]
tree
stow
neovim
emacs
bat
dfc
sudo
alacritty
bash
zsh
yay
zip
awk
sed
stress
lsd
git
curl
wget
glances
unzip
unrar
xorg-xmodmap
exa
volumeicon

discord
telegram-desktop

emacs
neovim
gimp
inkscape

firefox
flameshot
rsync
vifm
expac
pcmanfm
transmission-gtk
cmus
youtube-dl
zathura
neofetch
bat
dfc
cmus
cpupower
etcher
ffmpeg
git-annex
gufw
kdeconnect
newsboat
simple-scan
shellcheck
stow
tree
w3m
vlc
kdeconnect
ttf-mononoki
ttf-roboto-mono
ttf-cascadia-code
fzf
earlyoom
systemd-swap


[yay]
vscodium
ttf-mononoki
